#ifndef DODO_WRITER_HPP
#define DODO_WRITER_HPP

#include <cstdio>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include "dodo/cli.hpp"
#include "dodo/field.hpp"
#include "dodo/generators.hpp"

namespace dodo {

// A large user-space buffer in front of a FILE*. Generated bytes are appended
// here and flushed in big chunks with fwrite, which is the core of the constant
// memory, no-per-field-flush streaming strategy.
class OutputBuffer {
  public:
    explicit OutputBuffer(std::FILE* out, std::size_t capacity = 1u << 18);
    ~OutputBuffer();

    OutputBuffer(const OutputBuffer&) = delete;
    OutputBuffer& operator=(const OutputBuffer&) = delete;

    void append(std::string_view text);
    void append(char character);
    void flush();

  private:
    std::FILE* out_;
    std::size_t capacity_;
    std::string buffer_;
};

// Serializes rows in one output format. begin() receives the field list (for
// headers/keys/columns); write_row() must stay exception-free.
class Writer {
  public:
    virtual ~Writer() = default;
    virtual void begin(const std::vector<Field>& fields) = 0;
    virtual void write_row(const std::vector<Value>& values) = 0;
    virtual void end() = 0;
};

std::unique_ptr<Writer> make_writer(const CliOptions& options, OutputBuffer& output);

} // namespace dodo

#endif // DODO_WRITER_HPP
